### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by RaidMax** [synfinatic/netflow2ng#15]
```bash
# ./netflow2ng-v0.0.2-8-g887b99b-linux-x86_64 -addr 192.168.1.2 -port 2055
INFO[0000] Starting netflow2ng
INFO[0001] Started ZMQ listener on: tcp://*:5556
INFO[0001] Listening on UDP 192.168.1.2:2055             Type=NetFlow
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8619cc]

goroutine 1 [running]:
github.com/cloudflare/goflow/v3/utils.UDPRoutine(0x9b4cb2, 0x7, 0xc000152090, 0x1, 0x7ffcc729f60d, 0xb, 0x807, 0x0, 0xa74ac0, 0xc000132620, ...)
        /root/go/pkg/mod/github.com/cloudflare/goflow/v3@v3.4.2/utils/utils.go:184 +0x100c
github.com/cloudflare/goflow/v3/utils.(*StateNetFlow).FlowRoutine(0xc000067280, 0x1, 0x7ffcc729f60d, 0xb, 0x807, 0x0, 0x2, 0x0)
        /root/go/pkg/mod/github.com/cloudflare/goflow/v3@v3.4.2/utils/netflow.go:354 +0x15a
main.main()
        /root/netflow2ng/cmd/netflow2ng/netflow2ng.go:88 +0x4ca
```

Running on CentOS 8 `4.18.0-147.el8.x86_64 #1 SMP Wed Dec 4 21:51:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux` inside HyperV.
Thought it might be related to https://github.com/synfinatic/netflow2ng/issues/8 but this was compiled and running on same machine.

**Comment by synfinatic** [comment]
hmmm... that appears to be a bug in the netflow decoder in `cloudflare/goflow`  any chance you can reproduce and collect a pcap of the offending netflow packet triggering it?

**Comment by RaidMax** [comment]
It seems to occur immediately on boot. Here is a capture of the NetFlow packets coming from my router (Mikrotik/RouterOS)

```
14:49:31.912572 IP (tos 0x0, ttl 255, id 55020, offset 0, flags [none], proto UDP (17), length 1480)
    router.lan.iop > localhost.localdomain.iop: [no cksum] UDP, length 1452
        0x0000:  4500 05c8 d6ec 0000 ff11 5ae7 c0a8 01fe  E.........Z.....
        0x0010:  c0a8 0102 0807 0807 05b4 0000 0009 0013  ................
        0x0020:  05ac 40a4 60ef 31bc 0001 eb18 0000 0000  ..@.`.1.........
        0x0030:  0100 0598 05ac 0260 05ac 0260 0000 0006  .......`...`....
        0x0040:  0000 0194 0000 0001 0000 000e 334f 55ce  ............3OU.
        0x0050:  4b29 49c0 0600 c356 0659 c0a8 0192 0000  K)I....V.Y......
        0x0060:  02a0 687e 961d 71e4 8184 69b9 5b48 8f5a  ..h~..q...i.[H.Z
        0x0070:  cf81 3b33 4f55 cec0 a801 92c3 5606 5905  ..;3OU......V.Y.
        0x0080:  ac02 6005 ac02 6000 0000 0400 0001 8100  ..`...`.........
        0x0090:  0000 0e00 0000 01c0 a801 9233 4f55 ce06  ...........3OU..
        0x00a0:  0006 59c3 564b 2948 0100 0012 488f 5acf  ..Y.VK)H....H.Z.
        0x00b0:  813b 1c69 7a6f 1ce7 a068 7e96 1d71 4b29  .;.izo...h~..qK)
        0x00c0:  49c0 334f 55ce 0659 c356 05ac 0292 05ac  I.3OU..Y.V......
        0x00d0:  0292 0000 0006 0000 018c 0000 0001 0000  ................
        0x00e0:  000e 334f 55ce 4b29 49c0 0600 c358 0659  ..3OU.K)I....X.Y
        0x00f0:  c0a8 0192 0000 02a0 687e 961d 71e4 8184  ........h~..q...
        0x0100:  69b9 5b48 8f5a cf81 3b33 4f55 cec0 a801  i.[H.Z..;3OU....
        0x0110:  92c3 5806 5905 ac02 9205 ac02 9200 0000  ..X.Y...........
        0x0120:  0400 0001 8100 0000 0e00 0000 01c0 a801  ................
        0x0130:  9233 4f55 ce06 0006 59c3 584b 2948 0100  .3OU....Y.XK)H..
        0x0140:  0012 488f 5acf 813b 1c69 7a6f 1ce7 a068  ..H.Z..;.izo...h
        0x0150:  7e96 1d71 4b29 49c0 334f 55ce 0659 c358  ~..qK)I.3OU..Y.X
        0x0160:  05ac 0314 05ac 0314 0000 0001 0000 004a  ...............J
        0x0170:  0000 000e 0000 0000 c0a8 0148 c0a8 01fe  ...........H....
        0x0180:  1100 c2a9 0035 c0a8 01fe 0000 0048 8f5a  .....5.......H.Z
        0x0190:  cf81 3b8c 8590 77f5 0000 0000 0000 00c0  ..;...w.........
        0x01a0:  a801 48c0 a801 fec2 a900 3505 ac03 1405  ..H.......5.....
        0x01b0:  ac03 1400 0000 0100 0000 3f00 0000 0000  ..........?.....
        0x01c0:  0000 014b 2949 c044 5e9d 0b11 00be 5e00  ...K)I.D^.....^.
        0x01d0:  354b 2948 0100 0000 0000 0000 0000 0000  5K)H............
        0x01e0:  0000 0000 a068 7e96 1d71 4b29 49c0 445e  .....h~..qK)I.D^
        0x01f0:  9d0b be5e 0035 05ac 0328 05ac 0328 0000  ...^.5...(...(..
        0x0200:  0001 0000 006d 0000 0001 0000 0000 445e  .....m........D^
        0x0210:  9d0b 4b29 49c0 1128 0035 be5e 4b29 49c0  ..K)I..(.5.^K)I.
        0x0220:  0000 00a0 687e 961d 71e4 8184 69b9 5b00  ....h~..q...i.[.
        0x0230:  0000 0000 0044 5e9d 0b4b 2949 c000 35be  .....D^..K)I..5.
        0x0240:  5e05 ac03 2805 ac03 2800 0000 0100 0000  ^...(...(.......
        0x0250:  3f00 0000 0000 0000 0ec0 a801 fec0 a801  ?...............
        0x0260:  4811 0000 35c2 a9c0 a801 4800 0000 0000  H...5.....H.....
        0x0270:  0000 0000 0000 0000 0000 488f 5acf 813b  ..........H.Z..;
        0x0280:  c0a8 01fe c0a8 0148 0035 c2a9 05ac 0332  .......H.5.....2
        0x0290:  05ac 0332 0000 0001 0000 004a 0000 000e  ...2.......J....
        0x02a0:  0000 0001 c0a8 0148 445e 9c0b 1100 fcbe  .......HD^......
        0x02b0:  0035 4b29 4801 0000 0048 8f5a cf81 3b8c  .5K)H....H.Z..;.
        0x02c0:  8590 77f5 00a0 687e 961d 714b 2949 c044  ..w...h~..qK)I.D
        0x02d0:  5e9c 0bfc be00 3505 ac03 3205 ac03 3200  ^.....5...2...2.
        0x02e0:  0000 0100 0000 7800 0000 0100 0000 0e44  ......x........D
        0x02f0:  5e9c 0b4b 2949 c011 2800 35fc bec0 a801  ^..K)I..(.5.....
        0x0300:  4800 0000 a068 7e96 1d71 e481 8469 b95b  H....h~..q...i.[
        0x0310:  488f 5acf 813b 445e 9c0b c0a8 0148 0035  H.Z..;D^.....H.5
        0x0320:  fcbe 05ac 033c 05ac 033c 0000 0001 0000  .....<...<......
        0x0330:  004a 0000 000e 0000 0001 c0a8 0148 445e  .J...........HD^
        0x0340:  9d0b 1100 df05 0035 4b29 4801 0000 0048  .......5K)H....H
        0x0350:  8f5a cf81 3b8c 8590 77f5 00a0 687e 961d  .Z..;...w...h~..
        0x0360:  714b 2949 c044 5e9d 0bdf 0500 3505 ac03  qK)I.D^.....5...
        0x0370:  4605 ac03 4600 0000 0100 0000 7800 0000  F...F.......x...
        0x0380:  0100 0000 0e44 5e9d 0b4b 2949 c011 2800  .....D^..K)I..(.
        0x0390:  35df 05c0 a801 4800 0000 a068 7e96 1d71  5.....H....h~..q
        0x03a0:  e481 8469 b95b 488f 5acf 813b 445e 9d0b  ...i.[H.Z..;D^..
        0x03b0:  c0a8 0148 0035 df05 05ac 0350 05ac 0350  ...H.5.....P...P
        0x03c0:  0000 0001 0000 01a0 0000 000e 0000 0001  ................
        0x03d0:  c0a8 0148 d043 dede 1100 c8be 01bb 4b29  ...H.C........K)
        0x03e0:  4801 0000 0048 8f5a cf81 3b8c 8590 77f5  H....H.Z..;...w.
        0x03f0:  00a0 687e 961d 714b 2949 c0d0 43de dec8  ..h~..qK)I..C...
        0x0400:  be01 bb05 ac03 5005 ac03 5000 0000 0100  ......P...P.....
        0x0410:  0002 cc00 0000 0100 0000 0ed0 43de de4b  ............C..K
        0x0420:  2949 c011 0001 bbc8 bec0 a801 4800 0000  )I..........H...
        0x0430:  a068 7e96 1d71 e481 8469 b95b 488f 5acf  .h~..q...i.[H.Z.
        0x0440:  813b d043 dede c0a8 0148 01bb c8be 05ac  .;.C.....H......
        0x0450:  0364 05ac 0364 0000 0001 0000 0029 0000  .d...d.......)..
        0x0460:  000e 0000 0001 c0a8 0101 a29f 87e8 0600  ................
        0x0470:  0424 01bb 4b29 4801 0000 1048 8f5a cf81  .$..K)H....H.Z..
        0x0480:  3b00 1fbc 12e1 d9a0 687e 961d 714b 2949  ;.......h~..qK)I
        0x0490:  c0a2 9f87 e804 2401 bb05 ac03 6405 ac03  ......$.....d...
        0x04a0:  6400 0000 0100 0000 3400 0000 0100 0000  d.......4.......
        0x04b0:  0ea2 9f87 e84b 2949 c006 0001 bb04 24c0  .....K)I......$.
        0x04c0:  a801 0100 0010 a068 7e96 1d71 e481 8469  .......h~..q...i
        0x04d0:  b95b 488f 5acf 813b a29f 87e8 c0a8 0101  .[H.Z..;........
        0x04e0:  01bb 0424 05ac 03dc 05ab fbd0 0000 000a  ...$............
        0x04f0:  0000 229c 0000 0001 0000 000e ae66 0b15  .."..........f..
        0x0500:  4b29 49c0 1100 7120 7125 c0a8 0192 0000  K)I...q.q%......
        0x0510:  00a0 687e 961d 71e4 8184 69b9 5b48 8f5a  ..h~..q...i.[H.Z
        0x0520:  cf81 3bae 660b 15c0 a801 9271 2071 2505  ..;.f......q.q%.
        0x0530:  ac04 4005 abf6 c600 0000 0b00 0022 dc00  ..@.........."..
        0x0540:  0000 0100 0000 0e63 e1ca 224b 2949 c011  .......c.."K)I..
        0x0550:  0071 2071 25c0 a801 9200 0000 a068 7e96  .q.q%........h~.
        0x0560:  1d71 e481 8469 b95b 488f 5acf 813b 63e1  .q...i.[H.Z..;c.
        0x0570:  ca22 c0a8 0192 7120 7125 05ac 0440 05ab  ."....q.q%...@..
        0x0580:  f6c6 0000 0011 0000 3e6b 0000 000e 0000  ........>k......
        0x0590:  0001 c0a8 0192 63e1 ca22 1100 7125 7120  ......c.."..q%q.
        0x05a0:  4b29 4801 0000 0048 8f5a cf81 3b1c 697a  K)H....H.Z..;.iz
        0x05b0:  6f1c e7a0 687e 961d 714b 2949 c063 e1ca  o...h~..qK)I.c..
        0x05c0:  2271 2571 2020 4341                      "q%q..CA
14:49:31.912610 IP (tos 0x0, ttl 255, id 55019, offset 0, flags [none], proto UDP (17), length 268)
    router.lan.iop > localhost.localdomain.iop: [no cksum] UDP, length 240
        0x0000:  4500 010c d6eb 0000 ff11 5fa4 c0a8 01fe  E........._.....
        0x0010:  c0a8 0102 0807 0807 00f8 0000 0009 0002  ................
        0x0020:  05ac 40a4 60ef 31bc 0001 eb19 0000 0000  ..@.`.1.........
        0x0030:  0101 00dc 0626 2001 ec00 2100 0000 0000  .....&....!.....
        0x0040:  0000 0000 1100 0000 0001 2600 1700 337b  ..........&...3{
        0x0050:  0950 0810 ed77 0785 1a0a 0000 0000 0e26  .P...w.........&
        0x0060:  0017 0033 7b09 5008 10ed 7707 851a 0a06  ...3{.P...w.....
        0x0070:  1806 01bb 771b 8b91 cc00 0000 0000 05ac  ....w...........
        0x0080:  0166 05ac 0166 0000 006c 0000 0001 a068  .f...f...l.....h
        0x0090:  7e96 1d71 e481 8469 b95b 488f 5acf 813b  ~..q...i.[H.Z..;
        0x00a0:  0626 0017 0033 7b09 5008 10ed 7707 851a  .&...3{.P...w...
        0x00b0:  0a00 0000 000e 2620 01ec 0021 0000 0000  ......&....!....
        0x00c0:  0000 0000 0011 0000 0000 01fe 8000 0000  ................
        0x00d0:  0000 00e6 8184 fffe 69b8 0f06 1000 771b  ........i.....w.
        0x00e0:  01bb 2019 0100 0000 0000 05ac 018e 05ac  ................
        0x00f0:  018e 0000 003c 0000 0001 488f 5acf 813b  .....<....H.Z..;
        0x0100:  001f bc12 e1d9 a068 7e96 1d71            .......h~..q
14:49:32.912450 IP (tos 0x0, ttl 255, id 55021, offset 0, flags [none], proto UDP (17), length 1480)
    router.lan.iop > localhost.localdomain.iop: [no cksum] UDP, length 1452
        0x0000:  4500 05c8 d6ed 0000 ff11 5ae6 c0a8 01fe  E.........Z.....
        0x0010:  c0a8 0102 0807 0807 05b4 0000 0009 0013  ................
        0x0020:  05ac 448c 60ef 31bd 0001 eb1a 0000 0000  ..D.`.1.........
        0x0030:  0100 0598 05ac 0454 05ab f536 0000 000b  .......T...6....
        0x0040:  0000 21e0 0000 0001 0000 000e 5cec 3373  ..!.........\.3s
        0x0050:  4b29 49c0 1100 7120 7125 c0a8 0192 0000  K)I...q.q%......
        0x0060:  00a0 687e 961d 71e4 8184 69b9 5b48 8f5a  ..h~..q...i.[H.Z
        0x0070:  cf81 3b5c ec33 73c0 a801 9271 2071 2505  ..;\.3s....q.q%.
        0x0080:  ac04 5405 abf5 4a00 0000 1100 003e 6b00  ..T...J......>k.
        0x0090:  0000 0e00 0000 01c0 a801 925c ec33 7311  ...........\.3s.
        0x00a0:  0071 2571 204b 2948 0100 0000 488f 5acf  .q%q.K)H....H.Z.
        0x00b0:  813b 1c69 7a6f 1ce7 a068 7e96 1d71 4b29  .;.izo...h~..qK)
        0x00c0:  49c0 5cec 3373 7125 7120 05ac 0454 05ab  I.\.3sq%q....T..
        0x00d0:  fbf8 0000 0010 0000 3cb8 0000 000e 0000  ........<.......
        0x00e0:  0001 c0a8 0192 ae66 0b15 1100 7126 7120  .......f....q&q.
        0x00f0:  4b29 4801 0000 0048 8f5a cf81 3b1c 697a  K)H....H.Z..;.iz
        0x0100:  6f1c e7a0 687e 961d 714b 2949 c0ae 660b  o...h~..qK)I..f.
        0x0110:  1571 2671 2005 ac04 6805 abfb d000 0000  .q&q....h.......
        0x0120:  1000 003c b800 0000 0e00 0000 01c0 a801  ...<............
        0x0130:  92ae 660b 1511 0071 2571 204b 2948 0100  ..f....q%q.K)H..
        0x0140:  0000 488f 5acf 813b 1c69 7a6f 1ce7 a068  ..H.Z..;.izo...h
        0x0150:  7e96 1d71 4b29 49c0 ae66 0b15 7125 7120  ~..qK)I..f..q%q.
        0x0160:  05ac 0472 05ab f6f8 0000 000b 0000 22db  ...r..........".
        0x0170:  0000 0001 0000 000e 63e1 ca22 4b29 49c0  ........c.."K)I.
        0x0180:  1100 7120 7126 c0a8 0192 0000 00a0 687e  ..q.q&........h~
        0x0190:  961d 71e4 8184 69b9 5b48 8f5a cf81 3b63  ..q...i.[H.Z..;c
        0x01a0:  e1ca 22c0 a801 9271 2071 2605 ac04 7c05  .."....q.q&...|.
        0x01b0:  abf6 f800 0000 1100 003e 6700 0000 0e00  .........>g.....
        0x01c0:  0000 01c0 a801 9263 e1ca 2211 0071 2671  .......c.."..q&q
        0x01d0:  204b 2948 0100 0000 488f 5acf 813b 1c69  .K)H....H.Z..;.i
        0x01e0:  7a6f 1ce7 a068 7e96 1d71 4b29 49c0 63e1  zo...h~..qK)I.c.
        0x01f0:  ca22 7126 7120 05ac 0486 05ab f568 0000  ."q&q........h..
        0x0200:  000b 0000 21e0 0000 0001 0000 000e 5cec  ....!.........\.
        0x0210:  3373 4b29 49c0 1100 7120 7126 c0a8 0192  3sK)I...q.q&....
        0x0220:  0000 00a0 687e 961d 71e4 8184 69b9 5b48  ....h~..q...i.[H
        0x0230:  8f5a cf81 3b5c ec33 73c0 a801 9271 2071  .Z..;\.3s....q.q
        0x0240:  2605 ac04 8605 abf5 6800 0000 1100 003e  &.......h......>
        0x0250:  6800 0000 0e00 0000 01c0 a801 925c ec33  h............\.3
        0x0260:  7311 0071 2671 204b 2948 0100 0000 488f  s..q&q.K)H....H.
        0x0270:  5acf 813b 1c69 7a6f 1ce7 a068 7e96 1d71  Z..;.izo...h~..q
        0x0280:  4b29 49c0 5cec 3373 7126 7120 05ac 0490  K)I.\.3sq&q.....
        0x0290:  05ab fbf8 0000 000a 0000 229c 0000 0001  ..........".....
        0x02a0:  0000 000e ae66 0b15 4b29 49c0 1100 7120  .....f..K)I...q.
        0x02b0:  7126 c0a8 0192 0000 00a0 687e 961d 71e4  q&........h~..q.
        0x02c0:  8184 69b9 5b48 8f5a cf81 3bae 660b 15c0  ..i.[H.Z..;.f...
        0x02d0:  a801 9271 2071 2605 ac04 ae05 abf5 3600  ...q.q&.......6.
        0x02e0:  0000 0900 001c a800 0000 0100 0000 0e29  ...............)
        0x02f0:  648d 5c4b 2949 c011 0067 8571 26c0 a801  d.\K)I...g.q&...
        0x0300:  9200 0000 a068 7e96 1d71 e481 8469 b95b  .....h~..q...i.[
        0x0310:  488f 5acf 813b 2964 8d5c c0a8 0192 6785  H.Z..;)d.\....g.
        0x0320:  7126 05ac 04ae 05ab f536 0000 0011 0000  q&.......6......
        0x0330:  3e68 0000 000e 0000 0001 c0a8 0192 2964  >h............)d
        0x0340:  8d5c 1100 7126 6785 4b29 4801 0000 0048  .\..q&g.K)H....H
        0x0350:  8f5a cf81 3b1c 697a 6f1c e7a0 687e 961d  .Z..;.izo...h~..
        0x0360:  714b 2949 c029 648d 5c71 2667 8505 ac04  qK)I.)d.\q&g....
        0x0370:  b805 ac04 b800 0000 0600 0001 9400 0000  ................
        0x0380:  0100 0000 0e33 4f55 ce4b 2949 c006 00c3  .....3OU.K)I....
        0x0390:  6e06 59c0 a801 9200 0002 a068 7e96 1d71  n.Y........h~..q
        0x03a0:  e481 8469 b95b 488f 5acf 813b 334f 55ce  ...i.[H.Z..;3OU.
        0x03b0:  c0a8 0192 c36e 0659 05ac 04b8 05ac 04b8  .....n.Y........
        0x03c0:  0000 0004 0000 0181 0000 000e 0000 0001  ................
        0x03d0:  c0a8 0192 334f 55ce 0600 0659 c36e 4b29  ....3OU....Y.nK)
        0x03e0:  4801 0000 1248 8f5a cf81 3b1c 697a 6f1c  H....H.Z..;.izo.
        0x03f0:  e7a0 687e 961d 714b 2949 c033 4f55 ce06  ..h~..qK)I.3OU..
        0x0400:  59c3 6e05 ac04 ea05 ac04 ea00 0000 0600  Y.n.............
        0x0410:  0001 8c00 0000 0100 0000 0e33 4f55 ce4b  ...........3OU.K
        0x0420:  2949 c006 00c3 7006 59c0 a801 9200 0002  )I....p.Y.......
        0x0430:  a068 7e96 1d71 e481 8469 b95b 488f 5acf  .h~..q...i.[H.Z.
        0x0440:  813b 334f 55ce c0a8 0192 c370 0659 05ac  .;3OU......p.Y..
        0x0450:  04ea 05ac 04ea 0000 0004 0000 0181 0000  ................
        0x0460:  000e 0000 0001 c0a8 0192 334f 55ce 0600  ..........3OU...
        0x0470:  0659 c370 4b29 4801 0000 1248 8f5a cf81  .Y.pK)H....H.Z..
        0x0480:  3b1c 697a 6f1c e7a0 687e 961d 714b 2949  ;.izo...h~..qK)I
        0x0490:  c033 4f55 ce06 59c3 7005 ac07 1005 ac07  .3OU..Y.p.......
        0x04a0:  1000 0000 0600 0001 9400 0000 0100 0000  ................
        0x04b0:  0e33 4f55 ce4b 2949 c006 00c3 8406 59c0  .3OU.K)I......Y.
        0x04c0:  a801 9200 0002 a068 7e96 1d71 e481 8469  .......h~..q...i
        0x04d0:  b95b 488f 5acf 813b 334f 55ce c0a8 0192  .[H.Z..;3OU.....
        0x04e0:  c384 0659 05ac 0710 05ac 0710 0000 0004  ...Y............
        0x04f0:  0000 0181 0000 000e 0000 0001 c0a8 0192  ................
        0x0500:  334f 55ce 0600 0659 c384 4b29 4801 0000  3OU....Y..K)H...
        0x0510:  1248 8f5a cf81 3b1c 697a 6f1c e7a0 687e  .H.Z..;.izo...h~
        0x0520:  961d 714b 2949 c033 4f55 ce06 59c3 8405  ..qK)I.3OU..Y...
        0x0530:  ac07 4205 ac07 4200 0000 0600 0001 8c00  ..B...B.........
        0x0540:  0000 0100 0000 0e33 4f55 ce4b 2949 c006  .......3OU.K)I..
        0x0550:  00c3 8806 59c0 a801 9200 0002 a068 7e96  ....Y........h~.
        0x0560:  1d71 e481 8469 b95b 488f 5acf 813b 334f  .q...i.[H.Z..;3O
        0x0570:  55ce c0a8 0192 c388 0659 05ac 0742 05ac  U........Y...B..
        0x0580:  0742 0000 0004 0000 0181 0000 000e 0000  .B..............
        0x0590:  0001 c0a8 0192 334f 55ce 0600 0659 c388  ......3OU....Y..
        0x05a0:  4b29 4801 0000 1248 8f5a cf81 3b1c 697a  K)H....H.Z..;.iz
        0x05b0:  6f1c e7a0 687e 961d 714b 2949 c033 4f55  o...h~..qK)I.3OU
        0x05c0:  ce06 59c3 88fc 9595                      ..Y.....
```
Let me know if these help.

**Comment by RaidMax** [comment]
So I just got it working by changing the Netflow listen port to 2056.. Not sure exactly what was being sent to 2055 that would cause it to crash as the only thing I have setup is netflow from one router, but looks like using a different port has resolved the issue.
![image](https://user-images.githubusercontent.com/6732771/125681327-2fc7289f-a1d8-4f70-bdc0-255079d55efc.png)

**Comment by synfinatic** [comment]
Okay.  I'm going to close this issue.  If it happens again, please provide a pcap file `tcpdump -s0 -w netflow.pcap -i <interface>` rather than the hex dump so I can load it in wireshark for decoding.
